//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2016-06-06 00:04:33
namespace ODataRestaurantClient.RestaurantService.Models
{
    /// <summary>
    /// There are no comments for RestaurantSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RestaurantSingle")]
    public partial class RestaurantSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Restaurant>
    {
        /// <summary>
        /// Initialize a new RestaurantSingle object.
        /// </summary>
        public RestaurantSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RestaurantSingle object.
        /// </summary>
        public RestaurantSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RestaurantSingle object.
        /// </summary>
        public RestaurantSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Restaurant> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Restaurant in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Restaurant")]
    public partial class Restaurant : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Restaurant object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Restaurant CreateRestaurant(int ID)
        {
            Restaurant restaurant = new Restaurant();
            restaurant.Id = ID;
            return restaurant;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RateSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RateSingle")]
    public partial class RateSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Rate>
    {
        /// <summary>
        /// Initialize a new RateSingle object.
        /// </summary>
        public RateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RateSingle object.
        /// </summary>
        public RateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RateSingle object.
        /// </summary>
        public RateSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Rate> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Rate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Rate")]
    public partial class Rate : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Rate object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="restaurantId">Initial value of RestaurantId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="score">Initial value of Score.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Rate CreateRate(int ID, int restaurantId, int userId, int score)
        {
            Rate rate = new Rate();
            rate.Id = ID;
            rate.RestaurantId = restaurantId;
            rate.UserId = userId;
            rate.Score = score;
            return rate;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RestaurantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("restaurantId")]
        public int RestaurantId
        {
            get
            {
                return this._RestaurantId;
            }
            set
            {
                this.OnRestaurantIdChanging(value);
                this._RestaurantId = value;
                this.OnRestaurantIdChanged();
                this.OnPropertyChanged("restaurantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _RestaurantId;
        partial void OnRestaurantIdChanging(int value);
        partial void OnRestaurantIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("userId")]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("userId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Score in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("score")]
        public int Score
        {
            get
            {
                return this._Score;
            }
            set
            {
                this.OnScoreChanging(value);
                this._Score = value;
                this.OnScoreChanged();
                this.OnPropertyChanged("score");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Score;
        partial void OnScoreChanging(int value);
        partial void OnScoreChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ODataRestaurantClient.RestaurantService.Models.Restaurant as global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Restaurant> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataRestaurantClient.RestaurantService.Models.Restaurant as global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Restaurant> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataRestaurantClient.RestaurantService.Models.RestaurantSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataRestaurantClient.RestaurantService.Models.Rate as global::ODataRestaurantClient.RestaurantService.Models.RateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataRestaurantClient.RestaurantService.Models.RateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Rate> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataRestaurantClient.RestaurantService.Models.RateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataRestaurantClient.RestaurantService.Models.Rate as global::ODataRestaurantClient.RestaurantService.Models.RateSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataRestaurantClient.RestaurantService.Models.RateSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Rate> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::ODataRestaurantClient.RestaurantService.Models.RateSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace ODataRestaurantClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RestaurantService.Models", "ODataRestaurantClient.RestaurantService.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ODataRestaurantClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ODataRestaurantClient.RestaurantService.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("RestaurantService.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("RestaurantService.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ODataRestaurantClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Restaurants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Restaurants")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Restaurant> Restaurants
        {
            get
            {
                if ((this._Restaurants == null))
                {
                    this._Restaurants = base.CreateQuery<global::ODataRestaurantClient.RestaurantService.Models.Restaurant>("Restaurants");
                }
                return this._Restaurants;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Restaurant> _Restaurants;
        /// <summary>
        /// There are no comments for Rates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Rates")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Rate> Rates
        {
            get
            {
                if ((this._Rates == null))
                {
                    this._Rates = base.CreateQuery<global::ODataRestaurantClient.RestaurantService.Models.Rate>("Rates");
                }
                return this._Rates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataRestaurantClient.RestaurantService.Models.Rate> _Rates;
        /// <summary>
        /// There are no comments for Restaurants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRestaurants(global::ODataRestaurantClient.RestaurantService.Models.Restaurant restaurant)
        {
            base.AddObject("Restaurants", restaurant);
        }
        /// <summary>
        /// There are no comments for Rates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRates(global::ODataRestaurantClient.RestaurantService.Models.Rate rate)
        {
            base.AddObject("Rates", rate);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""RestaurantService.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Restaurant"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Rate"">
        <Key>
          <PropertyRef Name=""id"" />
        </Key>
        <Property Name=""id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""restaurantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""userId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""score"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""TestFunction"">
        <ReturnType Type=""Edm.String"" Unicode=""false"" />
      </Function>
      <Function Name=""MockRate"">
        <ReturnType Type=""Edm.String"" Unicode=""false"" />
      </Function>
      <Function Name=""RateCos"">
        <Parameter Name=""Melement"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.String"" Unicode=""false"" />
      </Function>
      <Function Name=""RateRestaurant"">
        <Parameter Name=""Token"" Type=""Edm.String"" Unicode=""false"" />
        <Parameter Name=""RestaurantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Parameter Name=""Score"" Type=""Edm.Int32"" Nullable=""false"" />
        <ReturnType Type=""Edm.String"" Unicode=""false"" />
      </Function>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Restaurants"" EntityType=""RestaurantService.Models.Restaurant"" />
        <EntitySet Name=""Rates"" EntityType=""RestaurantService.Models.Rate"" />
        <FunctionImport Name=""TestFunction"" Function=""Default.TestFunction"" IncludeInServiceDocument=""true"" />
        <FunctionImport Name=""MockRate"" Function=""Default.MockRate"" IncludeInServiceDocument=""true"" />
        <FunctionImport Name=""RateCos"" Function=""Default.RateCos"" IncludeInServiceDocument=""true"" />
        <FunctionImport Name=""RateRestaurant"" Function=""Default.RateRestaurant"" IncludeInServiceDocument=""true"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for TestFunction in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestFunction")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<string> TestFunction()
        {
            return this.CreateFunctionQuerySingle<string>("", "TestFunction", false);
        }
        /// <summary>
        /// There are no comments for MockRate in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("MockRate")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<string> MockRate()
        {
            return this.CreateFunctionQuerySingle<string>("", "MockRate", false);
        }
        /// <summary>
        /// There are no comments for RateCos in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("RateCos")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<string> RateCos(int Melement)
        {
            return this.CreateFunctionQuerySingle<string>("", "RateCos", false, new global::Microsoft.OData.Client.UriOperationParameter("Melement", Melement));
        }
        /// <summary>
        /// There are no comments for RateRestaurant in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("RateRestaurant")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<string> RateRestaurant(string Token, int RestaurantId, int Score)
        {
            return this.CreateFunctionQuerySingle<string>("", "RateRestaurant", false, new global::Microsoft.OData.Client.UriOperationParameter("Token", Token),
                    new global::Microsoft.OData.Client.UriOperationParameter("RestaurantId", RestaurantId),
                    new global::Microsoft.OData.Client.UriOperationParameter("Score", Score));
        }
    }
}
